### ISSUE TITLE
data connector error: unhandled params

### ISSUE THREAD

**Issue by jclaudino** [brentadamson/dataconnector#36]
Hi,

Out of the blue this error began appearing without changing anything to my configs. 

Also, I cannot click "cancel" or "save" when editing an API connector due to the "Documentation" button overlapping "Cancel" and "Save."

Thanks!

**Comment by brentadamson** [comment]
Thanks for reporting!

1. The unhandled params usually means you have a parameter (`+++1+++`) somewhere in your command but when you run it you aren't passing a placeholder for it. e.g. you run it as `=run("my-command")` rather than `=run("my-command", "something")`. If that isn't the case then we've got a bug somewhere.

2. That's weird! Do you have a lot of headers that you've added? What browser are you using?

**Comment by brentadamson** [comment]
Also, does zooming out or in help you be able to cancel/save it temporarily until we get it figured out?

**Comment by jclaudino** [comment]
I haven't changed any formulas from when it was previously working (at least not on purpose anyway!). When hovering over a cell with a formula error, i get the error "VALUE parameter 'Could not find a Data Connector command with name "TickerPrice"' cannot be parsed to number." That data connector definitely exists (check screenshot below)

I'm using the Brave browser on a 15" MacBook Pro. Nope zooming doesn't help. [Here's](https://imgur.com/a/DBxsARI) a screenshot for ya.

**Comment by jclaudino** [comment]
Fixed it! It was due to capitalized letters. Not sure why, but the data connectors lost their capitals (maybe a bug or maybe I unwittingly did something strange on my end). I was able to click the very top sliver of Save, but it's still overlapping.

Thanks for the quick reply and this awesome tool!

**Comment by brentadamson** [comment]
Great! BTW, I tried Brave browser on Ubuntu and it looks fine for me. I'll close this issue and open another issue for this. Since I can't verify it I'll let someone else attempt it...probably just needs a bottom margin or something.
