### ISSUE TITLE
Documentation button overlaps the cancel and save buttons on Brave browser

### ISSUE THREAD

**Issue by brentadamson** [brentadamson/dataconnector#37]
See https://github.com/brentadamson/dataconnector/issues/36

https://imgur.com/a/DBxsARI

Unfortunately, I'm not able to replicate this in Brave for Ubuntu but will accept a pull request that fixes it.

**Comment by mapierce** [comment]
Yep, same issue. I attached a video. I'm running Brave `1.25.70` on macOS `11.2.3`

https://user-images.githubusercontent.com/3449983/121377034-f2472600-c939-11eb-986d-ae1b161b84a2.mov

**Comment by brentadamson** [comment]
I'm wondering if it's the `https://github.com/brentadamson/dataconnector/blob/master/googlesheets/src/client/sidebar/components/Sidebar.jsx#L178` class that's causing the issue. I don't have any way to test it, though since I can't replicate it.

**Comment by mm12** [comment]
Same behavior in Chrome 93.0

**Comment by brentadamson** [comment]
I just deployed a fix. Can you check that it solved it? If not, can you send a screenshot?

**Comment by brentadamson** [comment]
Closing since I haven't received a response. Please re-open if it remains an issue.
