### ISSUE TITLE
Cannot Use. 

### ISSUE THREAD

**Issue by mm12** [brentadamson/dataconnector#45]
Addons > Data connector: Only the "help" button appears, and spacing looks off. 

Chrome 93

**Comment by brentadamson** [comment]
Thanks for reporting! That seems like it didn't install correctly. Can you try uninstalling and reinstalling it? Also, if you have multiple Gmail accounts (work, personal, etc) try logging out and logging in again. Sometimes, Sheets doesn't log you out completely.
