### ISSUE TITLE
Data Connector Add-on Permissions

### ISSUE THREAD

**Issue by nusaif** [brentadamson/dataconnector#60]
The Add-on requests full permission on all google drive sheets. while it should only request for permission on the sheets where the addon is installed into. as per my knowledge this can be done by adding the following lines to the  appsscript.json in google apps scripts.

"oauthScopes": [
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/script.external_request",
      "https://www.googleapis.com/auth/spreadsheets.currentonly"
    ],

**Comment by brentadamson** [comment]
I agree that we should limit the scope. Why is both drive.file and spreadsheets.currentonly necessary? Seems like we could just do the latter?

**Comment by brentadamson** [comment]
`spreadsheets.currentonly` by itself seems to work but where did you find it? It isn't listed in their OAuth2 scopes https://developers.google.com/identity/protocols/oauth2/scopes?hl=en#sheets

**Comment by brentadamson** [comment]
They both seem to work by themselves but I think I would prefer `spreadsheets.currentonly` if I could find some documentation on it so I know it's not a deprecated scope.

**Comment by brentadamson** [comment]
#61 seems to work. We can always roll it back if we find out that that OAuth2 scope is deprecated
